parkTartu/web/router.ex
defmodule ParkTartu.Router do
  use ParkTartu.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :auth_api do
     plug Guardian.Plug.EnsureAuthenticated, handler: ParkTartu.SessionAPIController
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug Guardian.Plug.VerifyHeader
    plug Guardian.Plug.LoadResource
  end

  scope "/", ParkTartu do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    resources "/parkings", ParkingController do
        resources "/parkingallocations", ParkingAllocationController ,only:  [:create]
        get "/parkingallocations/allocate", ParkingAllocationController, :allocate

    end

    get "/parkings", ParkingController, :index
    post "/parkings/search/", ParkingController, :search
  end

  scope "/api", ParkTartu do
    pipe_through :api
    post "/sessions", SessionAPIController, :create

    post "/sessions/register", SessionAPIController, :register
  end

  scope "/api", ParkTartu do
    pipe_through [:api, :auth_api]

    delete "/sessions/:id", SessionAPIController, :delete
    post "/sessions/update", SessionAPIController, :update
    post "/parkings", ParkingAPIController, :create
    post "/parkingallocations/", ParkingAllocationAPIController, :create
  end

end

parkTartu/web/models/parking.ex
defmodule ParkTartu.Parking do
  use ParkTartu.Web, :model

  schema "parkings" do
    field :name, :string
    field :latitude, :float
    field :longitude, :float
    field :street, :string
    field :zone, :string
    field :stopamount, :integer
    
    has_many :parkingallocations, ParkTartu.ParkingAllocation

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:name, :latitude, :longitude, :street, :zone, :stopamount])
    |> validate_required([:name, :latitude, :longitude, :street, :zone, :stopamount])
  end
end

parkTartu/web/controllers/parking_controller.ex
defmodule ParkTartu.ParkingController do
  use ParkTartu.Web, :controller
  alias ParkTartu.{Parking}

  def index(conn, _params) do
    render(conn, "index.html", parkings: [], changeset: Parking.changeset(%Parking{}))
  end
  def show(conn, _params) do
    render(conn, "index.html", parkings: [], changeset: Parking.changeset(%Parking{}))
  end

  def delete(conn, _params) do
    render(conn, "index.html", parkings: [], changeset: Parking.changeset(%Parking{}))
  end
  def edit(conn, _params) do
    render(conn, "index.html", parkings: [], changeset: Parking.changeset(%Parking{}))
  end
  def search(conn, params) do
    #IO.inspect(conn)
    %{"name" => name} = Map.get(params,"parking")

    changeset = Parking.changeset(%Parking{})

    query = from p in Parking,
            where: p.street == ^name,
            select: {p, (fragment("(SELECT COUNT(0) FROM parkingallocations
                                        WHERE parkingallocations.parking_id = ?)", p.id))}
    result = Repo.all(query)

    t= Enum.map(result, fn({x,y}) ->

      %{
        id: xid,
        name: xname,
        stopamount: xstopamount,
        street: xstreet,
        zone: xzone,
      } = x

      %{
        id: xid,
        name: xname,
        stopamount: xstopamount,
        street: xstreet,
        zone: xzone,
        cnt: y
      }

     end)

    render(conn, "index.html", parkings: t , changeset: changeset)
  end
end

parkTartu/web/views/parking_view.ex
defmodule ParkTartu.ParkingView do
    use ParkTartu.Web, :view
  end

parkTartu/web/templates/parking/index.html.eex
<h2>Listing parkings</h2>

<%= form_for @changeset, parking_path(@conn, :search), fn f -> %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, id: "parking_name", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= submit "Search", id: "submit_button", class: "btn btn-primary" %>
  </div>
<% end %>

<table class="table">
  <thead>
    <tr>

      <th>Name</th>
      <th>Street</th>
      <th>Zone</th>
      <th>StopAmount</th>
      <th>Filled StopAmount</th>

      <th>Operation</th>
    </tr>
  </thead>
  <tbody>
<%= for parking <- @parkings do %>
    <tr id="parkings">
  <td><%= parking.name %></td>
  <td><%= parking.street %></td>
  <td><%= parking.zone %></td>
  <td><%= parking.stopamount %></td>
  <td><%= parking.cnt %></td>

  <td> <span><%= link "Allocate", to: parking_parking_allocation_path(@conn, :allocate, parking.id), class: "btn btn-default btn-xs" %></span>  </td>
    </tr>
<% end %>
  </tbody>
</table>